dbt_project:
  outputs:
    dev:
      dataset: "{{ env_var('BIGQUERY_DATASET')}}"
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: "{{ env_var('GCP_PROJECT')}}"
      threads: 1
      type: bigquery
  target: dev
